name: Build and upload PDF file from LaTeX document
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v5
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: cv.tex
      - name: Rename PDF file
        run: mv cv.pdf "Bernardo Barzotto Zomer.pdf"
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Bernardo Barzotto Zomer
          path: "Bernardo Barzotto Zomer.pdf"
      - name: Release
        if: github.event_name == 'push' && github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: "Bernardo Barzotto Zomer.pdf"
          body_path: CHANGELOG.txt
          generate_release_notes: true
          make_latest: true